# Generated by Django 4.2.7 on 2025-02-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_match_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
    ]
